### ISSUE TITLE
\r\n

### ISSUE THREAD

**Issue by caiosm1005** [ChrisAckerman/slashes#1]
Hello,

First of all, thank you for this plugin.

I had trouble with the following snippet using `\r\n`:

    var slashes = require( "slashes" );
    var str = "Hello,\\r\\nworld!";
    console.log( slashes.strip( str ) );

The expected result was

    Hello,
    world!

But I got

    Hello,r
    world!

**Comment by yuvalsv** [comment]
Same here. Thanks.

**Comment by ChrisAckerman** [comment]
...3 years later.

I've completely re-written this library. The old `add()` and `strip()` methods still exist and are completely backwards compatible. The new `stripSlashes()` method handles this case.
